collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2702275
  brandStrength: 0.9830827
  lightness: 0.8502506
  brandColors:
    - '#FFFFFF'
    - '#01236A'
    - '#FD380E'
    - '#797979'
    - '#F9886F'
  rhythmicContrast: 0.9695267
typography_spectrum: 0.1616541
layout_spectrum: 0.2650376
name: COLCHONES LAMAS
