layout_spectrum: 0.9486216
typography_spectrum: 0.1616541
color:
  saturation: 0.2702275
  lightness: 0.8502506
  brandStrength: 0.8421053
  brandColors:
    - '#FEFEFE'
    - '#01236A'
    - '#FD380E'
    - '#A0ADC8'
    - '#5E74A0'
  rhythmicContrast: 0.9695267
name: COLCHONES LAMAS
